// Known bugs, mapped to graph pages via pageId. Seeded from qa-testing/Bug.md (empty repo).
// links: linear / jam / pr — any of them optional.
const BUGS = [
  { id: "BUG-015", title: "Devin settings — model/capability toggles rejected with 400 \"Fusion requires Devin Lite…\" (Ultra reverts on reload)", severity: "S2", status: "Open", pageId: "e-devin", caseIds: ["DEVIN-REG01"], links: { linear: "https://linear.app/cognition/issue/ENG-45170", jam: "https://jam.dev/c/demo-bug-015" }, notes: "Regression from #45170; whole settings payload re-validated so Ultra/Fast/native/lock-email all 400 and revert. Web search saves fine." },
  { id: "BUG-014", title: "Knowledge folder contents ignore sort — only top-level items reorder", severity: "S3", status: "Open", pageId: "e-knowledge", caseIds: ["KNOW-REG01"], links: { jam: "https://jam.dev/c/demo-bug-014" }, notes: "Sort applied to top-level list only, not nested folder children." },
  { id: "BUG-013", title: "Environment Upkeep tab triggers 404 API error — /api/beta/ endpoint not found", severity: "S4", status: "Open", pageId: "e-env", caseIds: ["ENV-REG01"], links: {}, notes: "Background call to /api/beta/ 404s when opening Upkeep tab; visible content still renders." },
  { id: "BUG-012", title: "No file size validation on profile picture upload — 20MB file accepted silently", severity: "S3", status: "Open", pageId: "prefs", caseIds: ["PREF-SMK01"], links: {}, notes: "No client-side size limit or error toast on avatar upload." },
  { id: "BUG-011", title: "Sub-org has no Sessions page in settings sidebar — direct navigation returns 404", severity: "S2", status: "Open", pageId: "s-settings", caseIds: [], links: {}, notes: "Enterprise sidebar has Sessions; sub-org doesn't, and /settings/sessions hard-404s." },
  { id: "BUG-010", title: "Snapshots \"Filter by script\" dropdown doesn't truncate long text — expands modal", severity: "S4", status: "Open", pageId: "e-env", caseIds: ["ENV-REG02"], links: {}, notes: "Long auto-generated URN option wraps and stretches the dropdown." },
  { id: "BUG-009", title: "Enterprise Sessions — clicking an active session from settings list crashes the app (React #185)", severity: "S2", status: "Open", pageId: "ent", caseIds: [], links: { jam: "https://jam.dev/c/demo-bug-009" }, notes: "Maximum update depth exceeded for active/running sessions; completed sessions open fine." },
  { id: "BUG-008", title: "Display language setting doesn't affect all UI elements — most content stays in English", severity: "S3", status: "Open", pageId: "prefs", caseIds: ["PREF-REG01"], links: {}, notes: "Sidebar translates; most content labels/descriptions hard-code English." },
  { id: "BUG-007", title: "Self-hosted GitLab \"Register app\" modal appears at top of page instead of centered", severity: "S3", status: "Open", pageId: "e-conn", caseIds: ["ECON-REG01"], links: {}, notes: "Modal renders at y=16px instead of vertically centered." },
  { id: "BUG-006", title: "Automation Network policy \"Add domain\" accepts invalid/garbage values with no validation", severity: "S3", status: "Open", pageId: "automations", caseIds: ["AUTO-REG01"], links: {}, notes: "javascript:alert(1), whitespace, schemes all accepted verbatim into a security allowlist." },
  { id: "BUG-005", title: "Missing line break rendering in IdP groups help text", severity: "S4", status: "Open", pageId: "user-groups-mrlw5j7x", caseIds: ["IDP-SMK01"], links: {}, notes: "\"provider.Please contact…\" concatenated; <br> without space." },
  { id: "BUG-004", title: "Grammatical error \"1 members\" should be \"1 member\" (singular)", severity: "S4", status: "Open", pageId: "landing", caseIds: ["ORGSEL-SMK01"], links: {}, notes: "Pluralization bug in org selector member counts." },
  { id: "BUG-003", title: "API keys and org IDs exposed in plaintext in Guardrails violation logs", severity: "S2", status: "Open", pageId: "security", caseIds: ["GUARD-REG01"], links: { linear: "https://linear.app/cognition/issue/ENG-demo-003" }, notes: "Guardrails blocks the message but the violation log shows the full unredacted secret." },
  { id: "BUG-002", title: "Duplicate service user name \"test-api key\" in Devin API settings", severity: "S3", status: "Open", pageId: "e-infra", caseIds: ["API-SMK01"], links: {}, notes: "Multiple service users share an identical name; no uniqueness warning." },
  { id: "BUG-001", title: "Duplicate organization \"kush-5\" in Organizations list", severity: "S3", status: "Open", pageId: "e-orgs", caseIds: ["ORG-SMK01"], links: {}, notes: "Two rows with the same org name; uniqueness not enforced at enterprise level." },
];
